// @ts-check
import { defineConfig } from 'astro/config';
import rehypeWatchCards from './src/plugins/rehype-watch-cards.mjs';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';

// https://astro.build/config
export default defineConfig({
  site: 'https://www.thewatchresource.com',

  integrations: [mdx(), sitemap()],

  markdown: {
    rehypePlugins: [rehypeWatchCards],
  },

  redirects: {
    // ── Reviews ──────────────────────────────────────────────────────────────
    '/alpina-alpiner-4-review/':                                        { destination: '/reviews/alpina-alpiner-4-review/',                                        status: 301 },
    '/ball-engineer-hydrocarbon-original-hands-on-review/':             { destination: '/reviews/ball-engineer-hydrocarbon-original-hands-on-review/',             status: 301 },
    '/ball-watches-a-comprehensive-brand-review/':                      { destination: '/reviews/ball-watches-a-comprehensive-brand-review/',                      status: 301 },
    '/bell-ross-br-05-gmt-review/':                                     { destination: '/reviews/bell-ross-br-05-gmt-review/',                                     status: 301 },
    '/bell-ross-br-05-review/':                                         { destination: '/reviews/bell-ross-br-05-review/',                                         status: 301 },
    '/benrus-orbit-robot-skindiver-review/':                            { destination: '/reviews/benrus-orbit-robot-skindiver-review/',                            status: 301 },
    '/benrus-sea-lord-hands-on-review/':                                { destination: '/reviews/benrus-sea-lord-hands-on-review/',                                status: 301 },
    '/benrus-ultra-deep-review/':                                       { destination: '/reviews/benrus-ultra-deep-review/',                                       status: 301 },
    '/benrus-watches-brand-history-and-review/':                        { destination: '/reviews/benrus-watches-brand-history-and-review/',                        status: 301 },
    '/brand-reviews/':                                                  { destination: '/reviews/brand-reviews/',                                                  status: 301 },
    '/bremont-watches-brand-review/':                                   { destination: '/reviews/bremont-watches-brand-review/',                                   status: 301 },
    '/certina-brand-review/':                                           { destination: '/reviews/certina-brand-review/',                                           status: 301 },
    '/circula-divesport-titanium-petrol-in-depth-review/':              { destination: '/reviews/circula-divesport-titanium-petrol-in-depth-review/',              status: 301 },
    '/doxa-sub-600t-caribbean-862-10-201-32-n-in-depth-review/':        { destination: '/reviews/doxa-sub-600t-caribbean-862-10-201-32-n-in-depth-review/',        status: 301 },
    '/doxa-watches-brand-review/':                                      { destination: '/reviews/doxa-watches-brand-review/',                                      status: 301 },
    '/echo-neutra-cortina-1956-3h-review/':                             { destination: '/reviews/echo-neutra-cortina-1956-3h-review/',                             status: 301 },
    '/furlan-marri-watches-brand-review/':                              { destination: '/reviews/furlan-marri-watches-brand-review/',                              status: 301 },
    '/hamilton-intra-matic-auto-chrono-review/':                        { destination: '/reviews/hamilton-intra-matic-auto-chrono-review/',                        status: 301 },
    '/hamilton-khaki-aviation-collection-review/':                      { destination: '/reviews/hamilton-khaki-aviation-collection-review/',                      status: 301 },
    '/hamilton-khaki-aviation-pilot-pioneer-h76205530-review/':         { destination: '/reviews/hamilton-khaki-aviation-pilot-pioneer-h76205530-review/',         status: 301 },
    '/hamilton-khaki-field-collection-review/':                         { destination: '/reviews/hamilton-khaki-field-collection-review/',                         status: 301 },
    '/hamilton-khaki-navy-collection-review/':                          { destination: '/reviews/hamilton-khaki-navy-collection-review/',                          status: 301 },
    '/hamilton-khaki-navy-scuba-auto-review/':                          { destination: '/reviews/hamilton-khaki-navy-scuba-auto-review/',                          status: 301 },
    '/hamilton-watches-brand-history-and-review/':                      { destination: '/reviews/hamilton-watches-brand-history-and-review/',                      status: 301 },
    '/in-depth-watch-reviews/':                                         { destination: '/reviews/in-depth-watch-reviews/',                                         status: 301 },
    '/jowissa-review/':                                                 { destination: '/reviews/jowissa-review/',                                                 status: 301 },
    '/kuoe-old-smith-90-007-in-depth-review/':                          { destination: '/reviews/kuoe-old-smith-90-007-in-depth-review/',                          status: 301 },
    '/laco-frankfurt-gmt-review/':                                      { destination: '/reviews/laco-frankfurt-gmt-review/',                                      status: 301 },
    '/laco-hamburg-din-8330-ref-862164-pilot-watch-in-depth-review/':   { destination: '/reviews/laco-hamburg-din-8330-ref-862164-pilot-watch-in-depth-review/',   status: 301 },
    '/laco-squad-watches-review/':                                      { destination: '/reviews/laco-squad-watches-review/',                                      status: 301 },
    '/laco-watches-brand-review/':                                      { destination: '/reviews/laco-watches-brand-review/',                                      status: 301 },
    '/le-forban-securite-mer-rochelaise-review/':                       { destination: '/reviews/le-forban-securite-mer-rochelaise-review/',                       status: 301 },
    '/le-forban-securite-mer-the-malouine-review/':                     { destination: '/reviews/le-forban-securite-mer-the-malouine-review/',                     status: 301 },
    '/longines-conquest-41-mm-l3-830-4-02-6-review/':                   { destination: '/reviews/longines-conquest-41-mm-l3-830-4-02-6-review/',                   status: 301 },
    '/lorca-model-no-1-gmt-review/':                                    { destination: '/reviews/lorca-model-no-1-gmt-review/',                                    status: 301 },
    '/maen-manhattan-37-m2-grey-ice-hands-on-review/':                  { destination: '/reviews/maen-manhattan-37-m2-grey-ice-hands-on-review/',                  status: 301 },
    '/minus-8-diver-2-0-review/':                                       { destination: '/reviews/minus-8-diver-2-0-review/',                                       status: 301 },
    '/muhle-glashutte-teutonia-sport-ii-racing-green-in-depth-review/': { destination: '/reviews/muhle-glashutte-teutonia-sport-ii-racing-green-in-depth-review/', status: 301 },
    '/nezumi-voiture-review/':                                          { destination: '/reviews/nezumi-voiture-review/',                                          status: 301 },
    '/nivada-grenchen-brand-review/':                                   { destination: '/reviews/nivada-grenchen-brand-review/',                                   status: 301 },
    '/norqain-adventure-sport-review/':                                 { destination: '/reviews/norqain-adventure-sport-review/',                                 status: 301 },
    '/norqain-freedom-chrono-60-review/':                               { destination: '/reviews/norqain-freedom-chrono-60-review/',                               status: 301 },
    '/norqain-watches-brand-history-and-review/':                       { destination: '/reviews/norqain-watches-brand-history-and-review/',                       status: 301 },
    '/norqain-wild-one-42-mm-khaki-review/':                            { destination: '/reviews/norqain-wild-one-42-mm-khaki-review/',                            status: 301 },
    '/ollech-wajs-brand-review/':                                       { destination: '/reviews/ollech-wajs-brand-review/',                                       status: 301 },
    '/rado-review/':                                                    { destination: '/reviews/rado-review/',                                                    status: 301 },
    '/raymond-weil-freelancer-gmt-worldtimer-review-a-must-have-gmt-watch/': { destination: '/reviews/raymond-weil-freelancer-gmt-worldtimer-review-a-must-have-gmt-watch/', status: 301 },
    '/raymond-weil-review/':                                            { destination: '/reviews/raymond-weil-review/',                                            status: 301 },
    '/review-longines-legend-diver/':                                   { destination: '/reviews/review-longines-legend-diver/',                                   status: 301 },
    '/review-spinnaker-dumas/':                                         { destination: '/reviews/review-spinnaker-dumas/',                                         status: 301 },
    '/serica-watches-brand-review-shopping-guide/':                     { destination: '/reviews/serica-watches-brand-review-shopping-guide/',                     status: 301 },
    '/shinola-runwell-41-review/':                                      { destination: '/reviews/shinola-runwell-41-review/',                                      status: 301 },
    '/sinn-104-st-sa-w-104-012-in-depth-review/':                       { destination: '/reviews/sinn-104-st-sa-w-104-012-in-depth-review/',                       status: 301 },
    '/spinnaker-watches-review-everything-you-need-to-know/':           { destination: '/reviews/spinnaker-watches-review-everything-you-need-to-know/',           status: 301 },
    '/sternglas-marus-black-review/':                                   { destination: '/reviews/sternglas-marus-black-review/',                                   status: 301 },
    '/sternglas-tachymeter-review/':                                    { destination: '/reviews/sternglas-tachymeter-review/',                                    status: 301 },
    '/sternglas-watches-brand-review/':                                 { destination: '/reviews/sternglas-watches-brand-review/',                                 status: 301 },
    '/szanto-watches-brand-history-and-review/':                        { destination: '/reviews/szanto-watches-brand-history-and-review/',                        status: 301 },
    '/timex-watches-review-brand-history-and-review/':                  { destination: '/reviews/timex-watches-review-brand-history-and-review/',                  status: 301 },
    '/tissot-watches-brand-history-and-review/':                        { destination: '/reviews/tissot-watches-brand-history-and-review/',                        status: 301 },
    '/undone-review/':                                                  { destination: '/reviews/undone-review/',                                                  status: 301 },
    '/unimatic-u4-classic-hands-on-review/':                            { destination: '/reviews/unimatic-u4-classic-hands-on-review/',                            status: 301 },
    '/unimatic-watches-brand-review/':                                  { destination: '/reviews/unimatic-watches-brand-review/',                                  status: 301 },
    '/vaer-d5-meridian-navy-diver-review/':                             { destination: '/reviews/vaer-d5-meridian-navy-diver-review/',                             status: 301 },
    '/vaer-r1-racing-chronograph-review/':                              { destination: '/reviews/vaer-r1-racing-chronograph-review/',                              status: 301 },
    '/vaer-s3-tradition-review/':                                       { destination: '/reviews/vaer-s3-tradition-review/',                                       status: 301 },
    '/vaer-watches-brand-history-and-review/':                          { destination: '/reviews/vaer-watches-brand-history-and-review/',                          status: 301 },
    '/vero-x-realtree-tide-tracker-compass-blue-in-depth-review/':      { destination: '/reviews/vero-x-realtree-tide-tracker-compass-blue-in-depth-review/',      status: 301 },
    '/vero-x-realtree-tide-tracker-outpost-black-hands-on-review/':     { destination: '/reviews/vero-x-realtree-tide-tracker-outpost-black-hands-on-review/',     status: 301 },
    '/vero-x-scout-motors-workhorse-chronograph-in-depth-review/':      { destination: '/reviews/vero-x-scout-motors-workhorse-chronograph-in-depth-review/',      status: 301 },
    '/victorinox-air-pro-automatic-ref-242003-in-depth-review/':        { destination: '/reviews/victorinox-air-pro-automatic-ref-242003-in-depth-review/',        status: 301 },
    '/victorinox-airboss-collection-review/':                           { destination: '/reviews/victorinox-airboss-collection-review/',                           status: 301 },
    '/victorinox-alliance-collection-review/':                          { destination: '/reviews/victorinox-alliance-collection-review/',                          status: 301 },
    '/victorinox-fieldforce-collection-review/':                        { destination: '/reviews/victorinox-fieldforce-collection-review/',                        status: 301 },
    '/victorinox-i-n-o-x-collection-review/':                          { destination: '/reviews/victorinox-i-n-o-x-collection-review/',                          status: 301 },
    '/victorinox-journey-1884-review-a-partner-for-all-adventures/':    { destination: '/reviews/victorinox-journey-1884-review-a-partner-for-all-adventures/',    status: 301 },
    '/victorinox-maverick-collection-review/':                          { destination: '/reviews/victorinox-maverick-collection-review/',                          status: 301 },
    '/victorinox-review/':                                              { destination: '/reviews/victorinox-review/',                                              status: 301 },
    '/william-wood-watches-review-brand-history-and-review/':           { destination: '/reviews/william-wood-watches-review-brand-history-and-review/',           status: 301 },
    '/yema-watches-brand-review-history-and-buyers-guide/':             { destination: '/reviews/yema-watches-brand-review-history-and-buyers-guide/',             status: 301 },
    '/zodiac-super-sea-wolf-pro-diver-review/':                         { destination: '/reviews/zodiac-super-sea-wolf-pro-diver-review/',                         status: 301 },
    '/zodiac-watches-brand-history-and-review/':                        { destination: '/reviews/zodiac-watches-brand-history-and-review/',                        status: 301 },
    '/zrc-watches-brand-review-buyers-guide/':                          { destination: '/reviews/zrc-watches-brand-review-buyers-guide/',                          status: 301 },

    // ── Guides ───────────────────────────────────────────────────────────────
    '/best-affordable-dive-watches/':                                   { destination: '/guides/best-affordable-dive-watches/',                                   status: 301 },
    '/best-affordable-everyday-watches/':                               { destination: '/guides/best-affordable-everyday-watches/',                               status: 301 },
    '/best-affordable-racing-watches/':                                 { destination: '/guides/best-affordable-racing-watches/',                                 status: 301 },
    '/best-american-watch-brands/':                                     { destination: '/guides/best-american-watch-brands/',                                     status: 301 },
    '/best-automatic-watches-under-1000/':                              { destination: '/guides/best-automatic-watches-under-1000/',                              status: 301 },
    '/best-automatic-watches-under-500/':                               { destination: '/guides/best-automatic-watches-under-500/',                               status: 301 },
    '/best-automotive-inspired-watches/':                               { destination: '/guides/best-automotive-inspired-watches/',                               status: 301 },
    '/best-bauhaus-watches-for-minimalist-fans/':                       { destination: '/guides/best-bauhaus-watches-for-minimalist-fans/',                       status: 301 },
    '/best-brown-dial-watches/':                                        { destination: '/guides/best-brown-dial-watches/',                                        status: 301 },
    '/best-dive-watches-under-1000/':                                   { destination: '/guides/best-dive-watches-under-1000/',                                   status: 301 },
    '/best-dive-watches-under-2000/':                                   { destination: '/guides/best-dive-watches-under-2000/',                                   status: 301 },
    '/best-dive-watches-under-500/':                                    { destination: '/guides/best-dive-watches-under-500/',                                    status: 301 },
    '/best-dive-watches-under-5000/':                                   { destination: '/guides/best-dive-watches-under-5000/',                                   status: 301 },
    '/best-dress-watches-under-1000/':                                  { destination: '/guides/best-dress-watches-under-1000/',                                  status: 301 },
    '/best-dress-watches-under-500/':                                   { destination: '/guides/best-dress-watches-under-500/',                                   status: 301 },
    '/best-dress-watches-under-5000/':                                  { destination: '/guides/best-dress-watches-under-5000/',                                  status: 301 },
    '/best-everyday-watches-under-1000/':                               { destination: '/guides/best-everyday-watches-under-1000/',                               status: 301 },
    '/best-everyday-watches-under-500/':                                { destination: '/guides/best-everyday-watches-under-500/',                                status: 301 },
    '/best-field-watches-under-2000/':                                  { destination: '/guides/best-field-watches-under-2000/',                                  status: 301 },
    '/best-field-watches-under-500/':                                   { destination: '/guides/best-field-watches-under-500/',                                   status: 301 },
    '/best-field-watches-under-5000/':                                  { destination: '/guides/best-field-watches-under-5000/',                                  status: 301 },
    '/best-gmt-watches-under-1000/':                                    { destination: '/guides/best-gmt-watches-under-1000/',                                    status: 301 },
    '/best-gmt-watches-under-2000/':                                    { destination: '/guides/best-gmt-watches-under-2000/',                                    status: 301 },
    '/best-gmt-watches-under-500/':                                     { destination: '/guides/best-gmt-watches-under-500/',                                     status: 301 },
    '/best-gmt-watches-under-5000/':                                    { destination: '/guides/best-gmt-watches-under-5000/',                                    status: 301 },
    '/best-gray-dial-watches/':                                         { destination: '/guides/best-gray-dial-watches/',                                         status: 301 },
    '/best-green-dial-watches/':                                        { destination: '/guides/best-green-dial-watches/',                                        status: 301 },
    '/best-guilloche-dial-watches/':                                    { destination: '/guides/best-guilloche-dial-watches/',                                    status: 301 },
    '/best-moon-phase-watches/':                                        { destination: '/guides/best-moon-phase-watches/',                                        status: 301 },
    '/best-orange-dial-watches/':                                       { destination: '/guides/best-orange-dial-watches/',                                       status: 301 },
    '/best-outdoor-watches-for-all-price-points/':                      { destination: '/guides/best-outdoor-watches-for-all-price-points/',                      status: 301 },
    '/best-panda-dial-chronographs/':                                   { destination: '/guides/best-panda-dial-chronographs/',                                   status: 301 },
    '/best-pilot-watches-under-1000/':                                  { destination: '/guides/best-pilot-watches-under-1000/',                                  status: 301 },
    '/best-pilot-watches-under-2000/':                                  { destination: '/guides/best-pilot-watches-under-2000/',                                  status: 301 },
    '/best-pilot-watches-under-500/':                                   { destination: '/guides/best-pilot-watches-under-500/',                                   status: 301 },
    '/best-racing-watches-under-2000/':                                 { destination: '/guides/best-racing-watches-under-2000/',                                 status: 301 },
    '/best-racing-watches-under-500/':                                  { destination: '/guides/best-racing-watches-under-500/',                                  status: 301 },
    '/best-rectangular-watches/':                                       { destination: '/guides/best-rectangular-watches/',                                       status: 301 },
    '/best-red-dial-watches/':                                          { destination: '/guides/best-red-dial-watches/',                                          status: 301 },
    '/best-seiko-watches-the-ultimate-guide-to-seiko-watches/':         { destination: '/guides/best-seiko-watches-the-ultimate-guide-to-seiko-watches/',         status: 301 },
    '/best-super-compressor-style-dive-watches/':                       { destination: '/guides/best-super-compressor-style-dive-watches/',                       status: 301 },
    '/best-vintage-inspired-watches/':                                  { destination: '/guides/best-vintage-inspired-watches/',                                  status: 301 },
    '/best-white-dial-watches/':                                        { destination: '/guides/best-white-dial-watches/',                                        status: 301 },
    '/two-watch-collection-the-best-pairs-for-all-price-ranges/':       { destination: '/guides/two-watch-collection-the-best-pairs-for-all-price-ranges/',       status: 301 },

    // ── Comparisons ──────────────────────────────────────────────────────────
    '/comparison-hamilton-khaki-navy-scuba-vs-longines-hydroconquest/': { destination: '/comparisons/comparison-hamilton-khaki-navy-scuba-vs-longines-hydroconquest/', status: 301 },
    '/comparison-hamilton-khaki-navy-scuba-vs-mido-ocean-star-200/':    { destination: '/comparisons/comparison-hamilton-khaki-navy-scuba-vs-mido-ocean-star-200/',    status: 301 },
    '/comparison-hamilton-khaki-navy-scuba-vs-tissot-seastar-1000/':    { destination: '/comparisons/comparison-hamilton-khaki-navy-scuba-vs-tissot-seastar-1000/',    status: 301 },
    '/comparison-longines-hydroconquest-vs-mido-ocean-star-200/':       { destination: '/comparisons/comparison-longines-hydroconquest-vs-mido-ocean-star-200/',       status: 301 },
    '/comparison-longines-hydroconquest-vs-tag-heuer-aquaracer/':       { destination: '/comparisons/comparison-longines-hydroconquest-vs-tag-heuer-aquaracer/',       status: 301 },
    '/comparison-longines-hydroconquest-vs-tissot-seastar-1000/':       { destination: '/comparisons/comparison-longines-hydroconquest-vs-tissot-seastar-1000/',       status: 301 },
    '/comparison-tag-heuer-aquaracer-vs-oris-aquis/':                   { destination: '/comparisons/comparison-tag-heuer-aquaracer-vs-oris-aquis/',                   status: 301 },
    '/comparison-tissot-seastar-1000-vs-mido-ocean-star-200/':          { destination: '/comparisons/comparison-tissot-seastar-1000-vs-mido-ocean-star-200/',          status: 301 },
    '/longines-hydroconquest-vs-oris-aquis-date-the-ultimate-2000-diver-showdown/': { destination: '/comparisons/longines-hydroconquest-vs-oris-aquis-date-the-ultimate-2000-diver-showdown/', status: 301 },
    '/tag-heuer-aquaracer-200-vs-tudor-black-bay-which-everyday-diver-wins/': { destination: '/comparisons/tag-heuer-aquaracer-200-vs-tudor-black-bay-which-everyday-diver-wins/', status: 301 },

    // ── Alternatives ─────────────────────────────────────────────────────────
    '/alternatives/':                                { destination: '/alternatives/alternatives/',                                status: 301 },
    '/audemars-piguet-royal-oak-alternatives/':      { destination: '/alternatives/audemars-piguet-royal-oak-alternatives/',      status: 301 },
    '/breitling-navitimer-alternatives/':            { destination: '/alternatives/breitling-navitimer-alternatives/',            status: 301 },
    '/cartier-tank-alternatives/':                   { destination: '/alternatives/cartier-tank-alternatives/',                   status: 301 },
    '/omega-seamaster-alternatives/':                { destination: '/alternatives/omega-seamaster-alternatives/',                status: 301 },
    '/omega-speedmaster-alternatives/':              { destination: '/alternatives/omega-speedmaster-alternatives/',              status: 301 },
    '/rolex-explorer-alternatives/':                 { destination: '/alternatives/rolex-explorer-alternatives/',                 status: 301 },
    '/rolex-submariner-alternatives/':               { destination: '/alternatives/rolex-submariner-alternatives/',               status: 301 },
    '/tag-heuer-carrera-alternatives/':              { destination: '/alternatives/tag-heuer-carrera-alternatives/',              status: 301 },

    // ── Pages ─────────────────────────────────────────────────────────────────
    '/collections/':                                         { destination: '/pages/collections/',                                         status: 301 },
    '/guide-to-watch-straps/':                               { destination: '/pages/guide-to-watch-straps/',                               status: 301 },
    '/guides/':                                              { destination: '/pages/guides/',                                              status: 301 },
    '/how-to-change-your-watch-strap/':                      { destination: '/pages/how-to-change-your-watch-strap/',                      status: 301 },
    '/one-watch-collection-for-1000/':                       { destination: '/pages/one-watch-collection-for-1000/',                       status: 301 },
    '/one-watch-collection-for-10000/':                      { destination: '/pages/one-watch-collection-for-10000/',                      status: 301 },
    '/one-watch-collection-for-5000/':                       { destination: '/pages/one-watch-collection-for-5000/',                       status: 301 },
    '/one-watch-collection-the-guide-for-all-price-ranges/': { destination: '/pages/one-watch-collection-the-guide-for-all-price-ranges/', status: 301 },
    '/spinnaker-bradner-quality-dive-watch-at-an-affordable-price/': { destination: '/pages/spinnaker-bradner-quality-dive-watch-at-an-affordable-price/', status: 301 },
    '/ultimate-watch-guide-for-men/':                        { destination: '/pages/ultimate-watch-guide-for-men/',                        status: 301 },
    '/watch-basics/':                                        { destination: '/pages/watch-basics/',                                        status: 301 },
    '/watch-comparisons/':                                   { destination: '/pages/watch-comparisons/',                                   status: 301 },
    '/watch-wearing-rules-every-man-should-know/':           { destination: '/pages/watch-wearing-rules-every-man-should-know/',           status: 301 },
    '/watches-with-vintage-lume/':                           { destination: '/pages/watches-with-vintage-lume/',                           status: 301 },
    '/what-is-a-dive-watch/':                                { destination: '/pages/what-is-a-dive-watch/',                                status: 301 },
    '/what-is-a-pilot-watch/':                               { destination: '/pages/what-is-a-pilot-watch/',                               status: 301 },
    '/what-is-a-racing-watch/':                              { destination: '/pages/what-is-a-racing-watch/',                              status: 301 },
  },
});
